export const MOVIES = [
    "Le Parrain",
    "Les Évadés",
    "The Dark Knight: Le Chevalier Noir",
    "Le Parrain, 2ème partie",
    "Pulp Fiction",
    "La Liste de Schindler",
    "12 Hommes en colère",
    "Le Seigneur des anneaux : Le Retour du Roi",
    "Forrest Gump",
    "Le Seigneur des anneaux : La Communauté de l'anneau",
    "Star Wars, épisode V : L'Empire contre-attaque",
    "Inception",
    "Le Seigneur des anneaux : Les Deux Tours",
    "The Matrix",
    "Les Affranchis",
    "Vol au-dessus d'un nid de coucou",
    "Les Sept Samouraïs",
    "Seven",
    "La Cité de Dieu",
    "C'est un merveilleux film",
    "La vie est belle",
    "Le Silence des agneaux",
    "La Ligne verte",
    "Il faut sauver le soldat Ryan",
    "Le Prestige",
    "Gladiator",
    "American History X",
    "Les Infiltrés",
    "Interstellar",
    "Sosie!",
    "Fight Club",
    "Terminator 2: Judgment Day",
    "Retour vers le futur",
    "Le Roi lion",
    "Les Dents de la mer",
    "Rocky",
    "Terminator",
    "Piège de cristal",
    "Jurassic Park",
    "Le Silence des agneaux",
    "Will Hunting",
    "SOS Fantômes",
    "Les Aventuriers de l'arche perdue",
    "E.T. l'extra-terrestre",
    "Alien",
    "Shining",
    "Blade Runner",
    "2001 : L'Odyssée de l'espace",
    "L'Exorciste",
    "Dirty Dancing",
    "Grease",
    "Fever Saturday Night",
    "Footloose",
    "Flashdance",
    "Top Gun",
    "The Breakfast Club",
    "Seize bougies",
    "La Folle Journée de Ferris Bueller",
    "Pretty in Pink",
    "Retour vers le futur",
    "Indiana Jones et le Temple maudit",
    "Ghost",
    "Dirty Dancing",
    "Point Break",
    "The Bodyguard",
    "Titanic",
    "Forrest Gump",
    "The Truman Show",
    "Sixième Sens",
    "La Ligne verte",
    "American Beauty",
    "The Social Network",
    "Juno",
    "Les Avengers",
    "The Dark Knight Rises",
    "Jurassic World",
    "Star Wars : Le Réveil de la Force",
    "The Martian",
    "Black Panther",
    "Avengers: Infinity War",
    "Captain Marvel",
    "Les Gardiens de la Galaxie",
    "Iron Man",
    "Spider-Man: New Generation",
    "Le Roi Lion",
    "Aladdin",
    "La Petite Sirène",
    "Toy Story",
    "Le Monde de Nemo",
    "Là-haut",
    "Monstres et Cie",
    "Shrek",
    "Dragons",
    "Les Indestructibles",
    "Moi, moche et méchant",
    "Kung Fu Panda",
    "Ratatouille",
    "Wall-E",
    "Coco",
    "Vice-versa",
    "La Reine des neiges",
    "Vaiana, la légende du bout du monde",
    "Zootopie",
    "Le Livre de la jungle",
    "Cendrillon",
    "La Belle et la Bête",
    "La Belle au bois dormant",
    "Blanche-Neige et les Sept Nains",
    "La Mélodie du bonheur",
    "Le Magicien d'Oz",
    "Autant en emporte le vent",
]